# docker-compose.yml
version: '3'
networks:
  default:
    external:
      name: bot_instance_net
services:
  themagiq_bot_server:
    image: stephdgenius/themagiq_bot:latest
    build:
      context: .
      dockerfile: Dockerfile_themagiq_bot
    restart: always
  themagiq_bot_nginx:
    image: stephdgenius/themagiq_bot_nginx:latest
    build:
      context: .
      dockerfile: Dockerfile_themagiq_bot_nginx
    ports:
      - 80:80
    depends_on:
      - themagiq_bot_server
    restart: always